baseURL: "https://example.com"
languageCode: "fr-fr"
title: "Lise Marcy"
pygmentsstyle: 'monokai'

# Theme settings
theme: novela
paginate: 6
social:
  twitter: "@lise_marcy"
  instagram: "#"
  facebook: "Lise-Marcy"
  youtube: "#"
taxonomies:
  author: authors
